// DO NOT EDIT. generated by github.com/tinywasm/orm

package devbrowser

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/form/input"
)

var _schemaEmulateDeviceArgs = []fmt.Field{
		{Name: "mode", Type: fmt.FieldText, NotNull: true},
		{Name: "capture", Type: fmt.FieldBool},
		{Name: "selector", Type: fmt.FieldText},
	}

func (m *EmulateDeviceArgs) Schema() []fmt.Field { return _schemaEmulateDeviceArgs }

func (m *EmulateDeviceArgs) Pointers() []any {
	return []any{
		&m.Mode,
		&m.Capture,
		&m.Selector,
	}
}

func (m *EmulateDeviceArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaGetConsoleArgs = []fmt.Field{
		{Name: "lines", Type: fmt.FieldInt, Widget: input.Number()},
	}

func (m *GetConsoleArgs) Schema() []fmt.Field { return _schemaGetConsoleArgs }

func (m *GetConsoleArgs) Pointers() []any {
	return []any{
		&m.Lines,
	}
}

func (m *GetConsoleArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaNavigateArgs = []fmt.Field{
		{Name: "url", Type: fmt.FieldText, NotNull: true},
	}

func (m *NavigateArgs) Schema() []fmt.Field { return _schemaNavigateArgs }

func (m *NavigateArgs) Pointers() []any {
	return []any{
		&m.URL,
	}
}

func (m *NavigateArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaScreenshotArgs = []fmt.Field{
		{Name: "fullpage", Type: fmt.FieldBool},
	}

func (m *ScreenshotArgs) Schema() []fmt.Field { return _schemaScreenshotArgs }

func (m *ScreenshotArgs) Pointers() []any {
	return []any{
		&m.Fullpage,
	}
}

func (m *ScreenshotArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaInspectElementArgs = []fmt.Field{
		{Name: "selector", Type: fmt.FieldText, NotNull: true},
	}

func (m *InspectElementArgs) Schema() []fmt.Field { return _schemaInspectElementArgs }

func (m *InspectElementArgs) Pointers() []any {
	return []any{
		&m.Selector,
	}
}

func (m *InspectElementArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaClickElementArgs = []fmt.Field{
		{Name: "selector", Type: fmt.FieldText, NotNull: true},
		{Name: "wait_after", Type: fmt.FieldInt, Widget: input.Number()},
		{Name: "timeout", Type: fmt.FieldInt, Widget: input.Number()},
	}

func (m *ClickElementArgs) Schema() []fmt.Field { return _schemaClickElementArgs }

func (m *ClickElementArgs) Pointers() []any {
	return []any{
		&m.Selector,
		&m.WaitAfter,
		&m.Timeout,
	}
}

func (m *ClickElementArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaFillElementArgs = []fmt.Field{
		{Name: "selector", Type: fmt.FieldText, NotNull: true},
		{Name: "value", Type: fmt.FieldText, NotNull: true},
		{Name: "wait_after", Type: fmt.FieldInt, Widget: input.Number()},
		{Name: "timeout", Type: fmt.FieldInt, Widget: input.Number()},
	}

func (m *FillElementArgs) Schema() []fmt.Field { return _schemaFillElementArgs }

func (m *FillElementArgs) Pointers() []any {
	return []any{
		&m.Selector,
		&m.Value,
		&m.WaitAfter,
		&m.Timeout,
	}
}

func (m *FillElementArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaSwipeElementArgs = []fmt.Field{
		{Name: "selector", Type: fmt.FieldText, NotNull: true},
		{Name: "direction", Type: fmt.FieldText, NotNull: true},
		{Name: "distance", Type: fmt.FieldInt, NotNull: true, Widget: input.Number()},
	}

func (m *SwipeElementArgs) Schema() []fmt.Field { return _schemaSwipeElementArgs }

func (m *SwipeElementArgs) Pointers() []any {
	return []any{
		&m.Selector,
		&m.Direction,
		&m.Distance,
	}
}

func (m *SwipeElementArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaEvaluateJSArgs = []fmt.Field{
		{Name: "script", Type: fmt.FieldText, NotNull: true},
		{Name: "await_promise", Type: fmt.FieldBool},
	}

func (m *EvaluateJSArgs) Schema() []fmt.Field { return _schemaEvaluateJSArgs }

func (m *EvaluateJSArgs) Pointers() []any {
	return []any{
		&m.Script,
		&m.AwaitPromise,
	}
}

func (m *EvaluateJSArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaGetNetworkLogsArgs = []fmt.Field{
		{Name: "filter", Type: fmt.FieldText},
		{Name: "limit", Type: fmt.FieldInt, Widget: input.Number()},
	}

func (m *GetNetworkLogsArgs) Schema() []fmt.Field { return _schemaGetNetworkLogsArgs }

func (m *GetNetworkLogsArgs) Pointers() []any {
	return []any{
		&m.Filter,
		&m.Limit,
	}
}

func (m *GetNetworkLogsArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaGetErrorsArgs = []fmt.Field{
		{Name: "limit", Type: fmt.FieldInt, Widget: input.Number()},
	}

func (m *GetErrorsArgs) Schema() []fmt.Field { return _schemaGetErrorsArgs }

func (m *GetErrorsArgs) Pointers() []any {
	return []any{
		&m.Limit,
	}
}

func (m *GetErrorsArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaGetPerformanceArgs = []fmt.Field{
		{Name: "reserved", Type: fmt.FieldInt},
	}

func (m *GetPerformanceArgs) Schema() []fmt.Field { return _schemaGetPerformanceArgs }

func (m *GetPerformanceArgs) Pointers() []any {
	return []any{
		&m.Reserved,
	}
}

func (m *GetPerformanceArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaGetContentArgs = []fmt.Field{
		{Name: "reserved", Type: fmt.FieldInt},
	}

func (m *GetContentArgs) Schema() []fmt.Field { return _schemaGetContentArgs }

func (m *GetContentArgs) Pointers() []any {
	return []any{
		&m.Reserved,
	}
}

func (m *GetContentArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaEmptyArgs = []fmt.Field{
		{Name: "reserved", Type: fmt.FieldInt},
	}

func (m *EmptyArgs) Schema() []fmt.Field { return _schemaEmptyArgs }

func (m *EmptyArgs) Pointers() []any {
	return []any{
		&m.Reserved,
	}
}

func (m *EmptyArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaOpenBrowserArgs = []fmt.Field{
		{Name: "port", Type: fmt.FieldText},
		{Name: "https", Type: fmt.FieldBool},
	}

func (m *OpenBrowserArgs) Schema() []fmt.Field { return _schemaOpenBrowserArgs }

func (m *OpenBrowserArgs) Pointers() []any {
	return []any{
		&m.Port,
		&m.Https,
	}
}

func (m *OpenBrowserArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

var _schemaCloseBrowserArgs = []fmt.Field{
		{Name: "reserved", Type: fmt.FieldInt},
	}

func (m *CloseBrowserArgs) Schema() []fmt.Field { return _schemaCloseBrowserArgs }

func (m *CloseBrowserArgs) Pointers() []any {
	return []any{
		&m.Reserved,
	}
}

func (m *CloseBrowserArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

