// DO NOT EDIT. generated by github.com/tinywasm/orm

package devbrowser

import (
	"github.com/tinywasm/fmt"
)

func (m *EmulateDeviceArgs) ModelName() string {
	return "emulate_device_args"
}

var _schemaEmulateDeviceArgs = []fmt.Field{
		{Name: "mode", Type: fmt.FieldText, NotNull: true},
		{Name: "capture", Type: fmt.FieldBool},
		{Name: "selector", Type: fmt.FieldText},
	}

func (m *EmulateDeviceArgs) Schema() []fmt.Field { return _schemaEmulateDeviceArgs }

func (m *EmulateDeviceArgs) Pointers() []any { return []any{&m.Mode, &m.Capture, &m.Selector} }

func (m *EmulateDeviceArgs) IsNil() bool { return m == nil }

func (m *EmulateDeviceArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("mode", m.Mode)
	w.Bool("capture", m.Capture)
	w.String("selector", m.Selector)
}

func (m *EmulateDeviceArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("mode"); ok { m.Mode = v }
	if v, ok := r.Bool("capture"); ok { m.Capture = v }
	if v, ok := r.String("selector"); ok { m.Selector = v }
	return nil
}

type EmulateDeviceArgsList []*EmulateDeviceArgs

func (s *EmulateDeviceArgsList) Schema() []fmt.Field { return nil }
func (s *EmulateDeviceArgsList) Pointers() []any     { return nil }
func (s *EmulateDeviceArgsList) Len() int             { return len(*s) }
func (s *EmulateDeviceArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *EmulateDeviceArgsList) Append() fmt.Fielder  { v := &EmulateDeviceArgs{}; *s = append(*s, v); return v }
func (s *EmulateDeviceArgsList) IsNil() bool          { return s == nil }
func (s *EmulateDeviceArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *EmulateDeviceArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *EmulateDeviceArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func (m *GetConsoleArgs) ModelName() string {
	return "get_console_args"
}

var _schemaGetConsoleArgs = []fmt.Field{
		{Name: "lines", Type: fmt.FieldInt},
	}

func (m *GetConsoleArgs) Schema() []fmt.Field { return _schemaGetConsoleArgs }

func (m *GetConsoleArgs) Pointers() []any { return []any{&m.Lines} }

func (m *GetConsoleArgs) IsNil() bool { return m == nil }

func (m *GetConsoleArgs) EncodeFields(w fmt.FieldWriter) {
	w.Int("lines", int64(m.Lines))
}

func (m *GetConsoleArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.Int("lines"); ok { m.Lines = int(v) }
	return nil
}

type GetConsoleArgsList []*GetConsoleArgs

func (s *GetConsoleArgsList) Schema() []fmt.Field { return nil }
func (s *GetConsoleArgsList) Pointers() []any     { return nil }
func (s *GetConsoleArgsList) Len() int             { return len(*s) }
func (s *GetConsoleArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *GetConsoleArgsList) Append() fmt.Fielder  { v := &GetConsoleArgs{}; *s = append(*s, v); return v }
func (s *GetConsoleArgsList) IsNil() bool          { return s == nil }
func (s *GetConsoleArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *GetConsoleArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *NavigateArgs) ModelName() string {
	return "navigate_args"
}

var _schemaNavigateArgs = []fmt.Field{
		{Name: "url", Type: fmt.FieldText, NotNull: true},
	}

func (m *NavigateArgs) Schema() []fmt.Field { return _schemaNavigateArgs }

func (m *NavigateArgs) Pointers() []any { return []any{&m.URL} }

func (m *NavigateArgs) IsNil() bool { return m == nil }

func (m *NavigateArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("url", m.URL)
}

func (m *NavigateArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("url"); ok { m.URL = v }
	return nil
}

type NavigateArgsList []*NavigateArgs

func (s *NavigateArgsList) Schema() []fmt.Field { return nil }
func (s *NavigateArgsList) Pointers() []any     { return nil }
func (s *NavigateArgsList) Len() int             { return len(*s) }
func (s *NavigateArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *NavigateArgsList) Append() fmt.Fielder  { v := &NavigateArgs{}; *s = append(*s, v); return v }
func (s *NavigateArgsList) IsNil() bool          { return s == nil }
func (s *NavigateArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *NavigateArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *NavigateArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func (m *ScreenshotArgs) ModelName() string {
	return "screenshot_args"
}

var _schemaScreenshotArgs = []fmt.Field{
		{Name: "fullpage", Type: fmt.FieldBool},
	}

func (m *ScreenshotArgs) Schema() []fmt.Field { return _schemaScreenshotArgs }

func (m *ScreenshotArgs) Pointers() []any { return []any{&m.Fullpage} }

func (m *ScreenshotArgs) IsNil() bool { return m == nil }

func (m *ScreenshotArgs) EncodeFields(w fmt.FieldWriter) {
	w.Bool("fullpage", m.Fullpage)
}

func (m *ScreenshotArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.Bool("fullpage"); ok { m.Fullpage = v }
	return nil
}

type ScreenshotArgsList []*ScreenshotArgs

func (s *ScreenshotArgsList) Schema() []fmt.Field { return nil }
func (s *ScreenshotArgsList) Pointers() []any     { return nil }
func (s *ScreenshotArgsList) Len() int             { return len(*s) }
func (s *ScreenshotArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *ScreenshotArgsList) Append() fmt.Fielder  { v := &ScreenshotArgs{}; *s = append(*s, v); return v }
func (s *ScreenshotArgsList) IsNil() bool          { return s == nil }
func (s *ScreenshotArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *ScreenshotArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *InspectElementArgs) ModelName() string {
	return "inspect_element_args"
}

var _schemaInspectElementArgs = []fmt.Field{
		{Name: "selector", Type: fmt.FieldText, NotNull: true},
	}

func (m *InspectElementArgs) Schema() []fmt.Field { return _schemaInspectElementArgs }

func (m *InspectElementArgs) Pointers() []any { return []any{&m.Selector} }

func (m *InspectElementArgs) IsNil() bool { return m == nil }

func (m *InspectElementArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("selector", m.Selector)
}

func (m *InspectElementArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("selector"); ok { m.Selector = v }
	return nil
}

type InspectElementArgsList []*InspectElementArgs

func (s *InspectElementArgsList) Schema() []fmt.Field { return nil }
func (s *InspectElementArgsList) Pointers() []any     { return nil }
func (s *InspectElementArgsList) Len() int             { return len(*s) }
func (s *InspectElementArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *InspectElementArgsList) Append() fmt.Fielder  { v := &InspectElementArgs{}; *s = append(*s, v); return v }
func (s *InspectElementArgsList) IsNil() bool          { return s == nil }
func (s *InspectElementArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *InspectElementArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *InspectElementArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func (m *ClickElementArgs) ModelName() string {
	return "click_element_args"
}

var _schemaClickElementArgs = []fmt.Field{
		{Name: "selector", Type: fmt.FieldText, NotNull: true},
		{Name: "wait_after", Type: fmt.FieldInt},
		{Name: "timeout", Type: fmt.FieldInt},
	}

func (m *ClickElementArgs) Schema() []fmt.Field { return _schemaClickElementArgs }

func (m *ClickElementArgs) Pointers() []any { return []any{&m.Selector, &m.WaitAfter, &m.Timeout} }

func (m *ClickElementArgs) IsNil() bool { return m == nil }

func (m *ClickElementArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("selector", m.Selector)
	w.Int("wait_after", int64(m.WaitAfter))
	w.Int("timeout", int64(m.Timeout))
}

func (m *ClickElementArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("selector"); ok { m.Selector = v }
	if v, ok := r.Int("wait_after"); ok { m.WaitAfter = int(v) }
	if v, ok := r.Int("timeout"); ok { m.Timeout = int(v) }
	return nil
}

type ClickElementArgsList []*ClickElementArgs

func (s *ClickElementArgsList) Schema() []fmt.Field { return nil }
func (s *ClickElementArgsList) Pointers() []any     { return nil }
func (s *ClickElementArgsList) Len() int             { return len(*s) }
func (s *ClickElementArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *ClickElementArgsList) Append() fmt.Fielder  { v := &ClickElementArgs{}; *s = append(*s, v); return v }
func (s *ClickElementArgsList) IsNil() bool          { return s == nil }
func (s *ClickElementArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *ClickElementArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *ClickElementArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func (m *FillElementArgs) ModelName() string {
	return "fill_element_args"
}

var _schemaFillElementArgs = []fmt.Field{
		{Name: "selector", Type: fmt.FieldText, NotNull: true},
		{Name: "value", Type: fmt.FieldText, NotNull: true},
		{Name: "wait_after", Type: fmt.FieldInt},
		{Name: "timeout", Type: fmt.FieldInt},
	}

func (m *FillElementArgs) Schema() []fmt.Field { return _schemaFillElementArgs }

func (m *FillElementArgs) Pointers() []any { return []any{&m.Selector, &m.Value, &m.WaitAfter, &m.Timeout} }

func (m *FillElementArgs) IsNil() bool { return m == nil }

func (m *FillElementArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("selector", m.Selector)
	w.String("value", m.Value)
	w.Int("wait_after", int64(m.WaitAfter))
	w.Int("timeout", int64(m.Timeout))
}

func (m *FillElementArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("selector"); ok { m.Selector = v }
	if v, ok := r.String("value"); ok { m.Value = v }
	if v, ok := r.Int("wait_after"); ok { m.WaitAfter = int(v) }
	if v, ok := r.Int("timeout"); ok { m.Timeout = int(v) }
	return nil
}

type FillElementArgsList []*FillElementArgs

func (s *FillElementArgsList) Schema() []fmt.Field { return nil }
func (s *FillElementArgsList) Pointers() []any     { return nil }
func (s *FillElementArgsList) Len() int             { return len(*s) }
func (s *FillElementArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *FillElementArgsList) Append() fmt.Fielder  { v := &FillElementArgs{}; *s = append(*s, v); return v }
func (s *FillElementArgsList) IsNil() bool          { return s == nil }
func (s *FillElementArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *FillElementArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *FillElementArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func (m *SwipeElementArgs) ModelName() string {
	return "swipe_element_args"
}

var _schemaSwipeElementArgs = []fmt.Field{
		{Name: "selector", Type: fmt.FieldText, NotNull: true},
		{Name: "direction", Type: fmt.FieldText, NotNull: true},
		{Name: "distance", Type: fmt.FieldInt, NotNull: true},
	}

func (m *SwipeElementArgs) Schema() []fmt.Field { return _schemaSwipeElementArgs }

func (m *SwipeElementArgs) Pointers() []any { return []any{&m.Selector, &m.Direction, &m.Distance} }

func (m *SwipeElementArgs) IsNil() bool { return m == nil }

func (m *SwipeElementArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("selector", m.Selector)
	w.String("direction", m.Direction)
	w.Int("distance", int64(m.Distance))
}

func (m *SwipeElementArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("selector"); ok { m.Selector = v }
	if v, ok := r.String("direction"); ok { m.Direction = v }
	if v, ok := r.Int("distance"); ok { m.Distance = int(v) }
	return nil
}

type SwipeElementArgsList []*SwipeElementArgs

func (s *SwipeElementArgsList) Schema() []fmt.Field { return nil }
func (s *SwipeElementArgsList) Pointers() []any     { return nil }
func (s *SwipeElementArgsList) Len() int             { return len(*s) }
func (s *SwipeElementArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *SwipeElementArgsList) Append() fmt.Fielder  { v := &SwipeElementArgs{}; *s = append(*s, v); return v }
func (s *SwipeElementArgsList) IsNil() bool          { return s == nil }
func (s *SwipeElementArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *SwipeElementArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *SwipeElementArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func (m *EvaluateJSArgs) ModelName() string {
	return "evaluate_jsargs"
}

var _schemaEvaluateJSArgs = []fmt.Field{
		{Name: "script", Type: fmt.FieldText, NotNull: true},
		{Name: "await_promise", Type: fmt.FieldBool},
	}

func (m *EvaluateJSArgs) Schema() []fmt.Field { return _schemaEvaluateJSArgs }

func (m *EvaluateJSArgs) Pointers() []any { return []any{&m.Script, &m.AwaitPromise} }

func (m *EvaluateJSArgs) IsNil() bool { return m == nil }

func (m *EvaluateJSArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("script", m.Script)
	w.Bool("await_promise", m.AwaitPromise)
}

func (m *EvaluateJSArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("script"); ok { m.Script = v }
	if v, ok := r.Bool("await_promise"); ok { m.AwaitPromise = v }
	return nil
}

type EvaluateJSArgsList []*EvaluateJSArgs

func (s *EvaluateJSArgsList) Schema() []fmt.Field { return nil }
func (s *EvaluateJSArgsList) Pointers() []any     { return nil }
func (s *EvaluateJSArgsList) Len() int             { return len(*s) }
func (s *EvaluateJSArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *EvaluateJSArgsList) Append() fmt.Fielder  { v := &EvaluateJSArgs{}; *s = append(*s, v); return v }
func (s *EvaluateJSArgsList) IsNil() bool          { return s == nil }
func (s *EvaluateJSArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *EvaluateJSArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *EvaluateJSArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

func (m *GetNetworkLogsArgs) ModelName() string {
	return "get_network_logs_args"
}

var _schemaGetNetworkLogsArgs = []fmt.Field{
		{Name: "filter", Type: fmt.FieldText},
		{Name: "limit", Type: fmt.FieldInt},
	}

func (m *GetNetworkLogsArgs) Schema() []fmt.Field { return _schemaGetNetworkLogsArgs }

func (m *GetNetworkLogsArgs) Pointers() []any { return []any{&m.Filter, &m.Limit} }

func (m *GetNetworkLogsArgs) IsNil() bool { return m == nil }

func (m *GetNetworkLogsArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("filter", m.Filter)
	w.Int("limit", int64(m.Limit))
}

func (m *GetNetworkLogsArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("filter"); ok { m.Filter = v }
	if v, ok := r.Int("limit"); ok { m.Limit = int(v) }
	return nil
}

type GetNetworkLogsArgsList []*GetNetworkLogsArgs

func (s *GetNetworkLogsArgsList) Schema() []fmt.Field { return nil }
func (s *GetNetworkLogsArgsList) Pointers() []any     { return nil }
func (s *GetNetworkLogsArgsList) Len() int             { return len(*s) }
func (s *GetNetworkLogsArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *GetNetworkLogsArgsList) Append() fmt.Fielder  { v := &GetNetworkLogsArgs{}; *s = append(*s, v); return v }
func (s *GetNetworkLogsArgsList) IsNil() bool          { return s == nil }
func (s *GetNetworkLogsArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *GetNetworkLogsArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *GetErrorsArgs) ModelName() string {
	return "get_errors_args"
}

var _schemaGetErrorsArgs = []fmt.Field{
		{Name: "limit", Type: fmt.FieldInt},
	}

func (m *GetErrorsArgs) Schema() []fmt.Field { return _schemaGetErrorsArgs }

func (m *GetErrorsArgs) Pointers() []any { return []any{&m.Limit} }

func (m *GetErrorsArgs) IsNil() bool { return m == nil }

func (m *GetErrorsArgs) EncodeFields(w fmt.FieldWriter) {
	w.Int("limit", int64(m.Limit))
}

func (m *GetErrorsArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.Int("limit"); ok { m.Limit = int(v) }
	return nil
}

type GetErrorsArgsList []*GetErrorsArgs

func (s *GetErrorsArgsList) Schema() []fmt.Field { return nil }
func (s *GetErrorsArgsList) Pointers() []any     { return nil }
func (s *GetErrorsArgsList) Len() int             { return len(*s) }
func (s *GetErrorsArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *GetErrorsArgsList) Append() fmt.Fielder  { v := &GetErrorsArgs{}; *s = append(*s, v); return v }
func (s *GetErrorsArgsList) IsNil() bool          { return s == nil }
func (s *GetErrorsArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *GetErrorsArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *GetPerformanceArgs) ModelName() string {
	return "get_performance_args"
}

var _schemaGetPerformanceArgs = []fmt.Field{
		{Name: "reserved", Type: fmt.FieldInt},
	}

func (m *GetPerformanceArgs) Schema() []fmt.Field { return _schemaGetPerformanceArgs }

func (m *GetPerformanceArgs) Pointers() []any { return []any{&m.Reserved} }

func (m *GetPerformanceArgs) IsNil() bool { return m == nil }

func (m *GetPerformanceArgs) EncodeFields(w fmt.FieldWriter) {
	w.Int("reserved", int64(m.Reserved))
}

func (m *GetPerformanceArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.Int("reserved"); ok { m.Reserved = int(v) }
	return nil
}

type GetPerformanceArgsList []*GetPerformanceArgs

func (s *GetPerformanceArgsList) Schema() []fmt.Field { return nil }
func (s *GetPerformanceArgsList) Pointers() []any     { return nil }
func (s *GetPerformanceArgsList) Len() int             { return len(*s) }
func (s *GetPerformanceArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *GetPerformanceArgsList) Append() fmt.Fielder  { v := &GetPerformanceArgs{}; *s = append(*s, v); return v }
func (s *GetPerformanceArgsList) IsNil() bool          { return s == nil }
func (s *GetPerformanceArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *GetPerformanceArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *GetContentArgs) ModelName() string {
	return "get_content_args"
}

var _schemaGetContentArgs = []fmt.Field{
		{Name: "reserved", Type: fmt.FieldInt},
	}

func (m *GetContentArgs) Schema() []fmt.Field { return _schemaGetContentArgs }

func (m *GetContentArgs) Pointers() []any { return []any{&m.Reserved} }

func (m *GetContentArgs) IsNil() bool { return m == nil }

func (m *GetContentArgs) EncodeFields(w fmt.FieldWriter) {
	w.Int("reserved", int64(m.Reserved))
}

func (m *GetContentArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.Int("reserved"); ok { m.Reserved = int(v) }
	return nil
}

type GetContentArgsList []*GetContentArgs

func (s *GetContentArgsList) Schema() []fmt.Field { return nil }
func (s *GetContentArgsList) Pointers() []any     { return nil }
func (s *GetContentArgsList) Len() int             { return len(*s) }
func (s *GetContentArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *GetContentArgsList) Append() fmt.Fielder  { v := &GetContentArgs{}; *s = append(*s, v); return v }
func (s *GetContentArgsList) IsNil() bool          { return s == nil }
func (s *GetContentArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *GetContentArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *EmptyArgs) ModelName() string {
	return "empty_args"
}

var _schemaEmptyArgs = []fmt.Field{
		{Name: "reserved", Type: fmt.FieldInt},
	}

func (m *EmptyArgs) Schema() []fmt.Field { return _schemaEmptyArgs }

func (m *EmptyArgs) Pointers() []any { return []any{&m.Reserved} }

func (m *EmptyArgs) IsNil() bool { return m == nil }

func (m *EmptyArgs) EncodeFields(w fmt.FieldWriter) {
	w.Int("reserved", int64(m.Reserved))
}

func (m *EmptyArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.Int("reserved"); ok { m.Reserved = int(v) }
	return nil
}

type EmptyArgsList []*EmptyArgs

func (s *EmptyArgsList) Schema() []fmt.Field { return nil }
func (s *EmptyArgsList) Pointers() []any     { return nil }
func (s *EmptyArgsList) Len() int             { return len(*s) }
func (s *EmptyArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *EmptyArgsList) Append() fmt.Fielder  { v := &EmptyArgs{}; *s = append(*s, v); return v }
func (s *EmptyArgsList) IsNil() bool          { return s == nil }
func (s *EmptyArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *EmptyArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *OpenBrowserArgs) ModelName() string {
	return "open_browser_args"
}

var _schemaOpenBrowserArgs = []fmt.Field{
		{Name: "port", Type: fmt.FieldText},
		{Name: "https", Type: fmt.FieldBool},
	}

func (m *OpenBrowserArgs) Schema() []fmt.Field { return _schemaOpenBrowserArgs }

func (m *OpenBrowserArgs) Pointers() []any { return []any{&m.Port, &m.Https} }

func (m *OpenBrowserArgs) IsNil() bool { return m == nil }

func (m *OpenBrowserArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("port", m.Port)
	w.Bool("https", m.Https)
}

func (m *OpenBrowserArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("port"); ok { m.Port = v }
	if v, ok := r.Bool("https"); ok { m.Https = v }
	return nil
}

type OpenBrowserArgsList []*OpenBrowserArgs

func (s *OpenBrowserArgsList) Schema() []fmt.Field { return nil }
func (s *OpenBrowserArgsList) Pointers() []any     { return nil }
func (s *OpenBrowserArgsList) Len() int             { return len(*s) }
func (s *OpenBrowserArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *OpenBrowserArgsList) Append() fmt.Fielder  { v := &OpenBrowserArgs{}; *s = append(*s, v); return v }
func (s *OpenBrowserArgsList) IsNil() bool          { return s == nil }
func (s *OpenBrowserArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *OpenBrowserArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *CloseBrowserArgs) ModelName() string {
	return "close_browser_args"
}

var _schemaCloseBrowserArgs = []fmt.Field{
		{Name: "reserved", Type: fmt.FieldInt},
	}

func (m *CloseBrowserArgs) Schema() []fmt.Field { return _schemaCloseBrowserArgs }

func (m *CloseBrowserArgs) Pointers() []any { return []any{&m.Reserved} }

func (m *CloseBrowserArgs) IsNil() bool { return m == nil }

func (m *CloseBrowserArgs) EncodeFields(w fmt.FieldWriter) {
	w.Int("reserved", int64(m.Reserved))
}

func (m *CloseBrowserArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.Int("reserved"); ok { m.Reserved = int(v) }
	return nil
}

type CloseBrowserArgsList []*CloseBrowserArgs

func (s *CloseBrowserArgsList) Schema() []fmt.Field { return nil }
func (s *CloseBrowserArgsList) Pointers() []any     { return nil }
func (s *CloseBrowserArgsList) Len() int             { return len(*s) }
func (s *CloseBrowserArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *CloseBrowserArgsList) Append() fmt.Fielder  { v := &CloseBrowserArgs{}; *s = append(*s, v); return v }
func (s *CloseBrowserArgsList) IsNil() bool          { return s == nil }
func (s *CloseBrowserArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *CloseBrowserArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

