package dom

// Code generated by cdproto-gen. DO NOT EDIT.

import (

	"encoding/json"
)

// PhysicalAxes containerSelector physical axes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-PhysicalAxes
type PhysicalAxes string

// String returns the PhysicalAxes as string value.
func (t PhysicalAxes) String() string {
	return string(t)
}

// PhysicalAxes values.
const (
	PhysicalAxesHorizontal PhysicalAxes = "Horizontal"
	PhysicalAxesVertical   PhysicalAxes = "Vertical"
	PhysicalAxesBoth       PhysicalAxes = "Both"
)

// MarshalJSON satisfies json.Marshaler.
func (t PhysicalAxes) MarshalJSON() ([]byte, error) {
	return json.Marshal(t)
}

// UnmarshalJSON satisfies json.Unmarshaler.
func (t *PhysicalAxes) UnmarshalJSON(buf []byte) error {
	return json.Unmarshal(buf, t)
}

// LogicalAxes containerSelector logical axes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-LogicalAxes
type LogicalAxes string

// String returns the LogicalAxes as string value.
func (t LogicalAxes) String() string {
	return string(t)
}

// LogicalAxes values.
const (
	LogicalAxesInline LogicalAxes = "Inline"
	LogicalAxesBlock  LogicalAxes = "Block"
	LogicalAxesBoth   LogicalAxes = "Both"
)

// MarshalJSON satisfies json.Marshaler.
func (t LogicalAxes) MarshalJSON() ([]byte, error) {
	return json.Marshal(t)
}

// UnmarshalJSON satisfies json.Unmarshaler.
func (t *LogicalAxes) UnmarshalJSON(buf []byte) error {
	return json.Unmarshal(buf, t)
}

// ScrollOrientation physical scroll orientation.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-ScrollOrientation
type ScrollOrientation string

// String returns the ScrollOrientation as string value.
func (t ScrollOrientation) String() string {
	return string(t)
}

// ScrollOrientation values.
const (
	ScrollOrientationHorizontal ScrollOrientation = "horizontal"
	ScrollOrientationVertical   ScrollOrientation = "vertical"
)

// MarshalJSON satisfies json.Marshaler.
func (t ScrollOrientation) MarshalJSON() ([]byte, error) {
	return json.Marshal(t)
}

// UnmarshalJSON satisfies json.Unmarshaler.
func (t *ScrollOrientation) UnmarshalJSON(buf []byte) error {
	return json.Unmarshal(buf, t)
}

// Quad an array of quad vertices, x immediately followed by y for each
// point, points clock-wise.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-Quad
type Quad []float64

// BoxModel box model.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-BoxModel
type BoxModel struct {
	Content      Quad              `json:"content"`                // Content box
	Padding      Quad              `json:"padding"`                // Padding box
	Border       Quad              `json:"border"`                 // Border box
	Margin       Quad              `json:"margin"`                 // Margin box
	Width        int64             `json:"width"`                  // Node width
	Height       int64             `json:"height"`                 // Node height
	ShapeOutside *ShapeOutsideInfo `json:"shapeOutside,omitempty"` // Shape outside coordinates
}

// ShapeOutsideInfo CSS Shape Outside details.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-ShapeOutsideInfo
type ShapeOutsideInfo struct {
	Bounds      Quad              `json:"bounds"`      // Shape bounds
	Shape       []json.RawMessage `json:"shape"`       // Shape coordinate details
	MarginShape []json.RawMessage `json:"marginShape"` // Margin shape bounds
}

// Rect Rectangle.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-Rect
type Rect struct {
	X      float64 `json:"x"`      // X coordinate
	Y      float64 `json:"y"`      // Y coordinate
	Width  float64 `json:"width"`  // Rectangle width
	Height float64 `json:"height"` // Rectangle height
}

// CSSComputedStyleProperty [no description].
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#type-CSSComputedStyleProperty
type CSSComputedStyleProperty struct {
	Name  string `json:"name"`  // Computed style property name.
	Value string `json:"value"` // Computed style property value.
}

// EnableIncludeWhitespace whether to include whitespaces in the children
// array of returned Nodes.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-enable
type EnableIncludeWhitespace string

// String returns the EnableIncludeWhitespace as string value.
func (t EnableIncludeWhitespace) String() string {
	return string(t)
}

// EnableIncludeWhitespace values.
const (
	EnableIncludeWhitespaceNone EnableIncludeWhitespace = "none"
	EnableIncludeWhitespaceAll  EnableIncludeWhitespace = "all"
)

// MarshalJSON satisfies json.Marshaler.
func (t EnableIncludeWhitespace) MarshalJSON() ([]byte, error) {
	return json.Marshal(t)
}

// UnmarshalJSON satisfies json.Unmarshaler.
func (t *EnableIncludeWhitespace) UnmarshalJSON(buf []byte) error {
	return json.Unmarshal(buf, t)
}

// GetElementByRelationRelation type of relation to get.
//
// See: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getElementByRelation
type GetElementByRelationRelation string

// String returns the GetElementByRelationRelation as string value.
func (t GetElementByRelationRelation) String() string {
	return string(t)
}

// GetElementByRelationRelation values.
const (
	GetElementByRelationRelationPopoverTarget GetElementByRelationRelation = "PopoverTarget"
)

// MarshalJSON satisfies json.Marshaler.
func (t GetElementByRelationRelation) MarshalJSON() ([]byte, error) {
	return json.Marshal(t)
}

// UnmarshalJSON satisfies json.Unmarshaler.
func (t *GetElementByRelationRelation) UnmarshalJSON(buf []byte) error {
	return json.Unmarshal(buf, t)
}
